# This workflow will build and test .NET projects and frontend code
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test

on: 
  workflow_dispatch: 
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Build Backend
    - name: Restore Backend dependencies
      run: dotnet restore
      working-directory: SolarWatch/

    - name: Build Backend
      run: dotnet build --no-restore
      working-directory: SolarWatch/

    # Build Frontend
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # You can adjust this to match your project's requirements

    - name: Install Frontend dependencies
      run: npm install
      working-directory: Frontend

    - name: Build Frontend
      run: npm run build
      working-directory: Frontend

    # Run Unit Tests
    - name: Run Unit Tests
      run: dotnet test --no-build --verbosity normal
      working-directory: SolarWatchTESTS/

    # Run Integration Tests
    - name: Run Integration Tests
      run: dotnet test --no-build --verbosity normal
      working-directory: SolarWatch_Integration_Tests/
